### PR TITLE
Updated sys-libs/libunwind to llvm-runtimes/libunwind to resolve a dependency mismatch

### PR DESCRIPTION
**Pull request by ThisNekoGuy**
Changed the category name for sys-libs/libunwind to llvm-runtimes/libunwind to resolve incompatibility with the upstream name.

### CODE REVIEW

**Comment by ThisNekoGuy** [comment]
Forgot to mention that this was for `emulation-games/yuzu`; whoops! :sweat_smile:

**Comment by Tatsh** [comment]
Could you do a `git commit --amend` and edit the message to have the prefix `games-emulation/yuzu: ` ? (and `git push --force`)

**Comment by Tatsh** [comment]
Also are there other packages needing this? Sudachi is basically Yuzu so it should need it to.

**Comment by ThisNekoGuy** [comment]
Running `grep -srin "sys-libs/llvm-libunwind" $PWD` in the repo only reveals Sudachi as the only other package:
```
/tmp/tatsh-overlay/games-emulation/sudachi/sudachi-1.0.11.ebuild:58:    llvm-libunwind? ( sys-libs/llvm-libunwind )
```

**Comment by Tatsh** [comment]
> Running `grep -srin "sys-libs/llvm-libunwind" $PWD` in the repo only reveals Sudachi as the only other package:
> 
> ```
> /tmp/tatsh-overlay/games-emulation/sudachi/sudachi-1.0.11.ebuild:58:    llvm-libunwind? ( sys-libs/llvm-libunwind )
> ```

Could you update that as well?

**Comment by ThisNekoGuy** [comment]
Yeah, I'm trying to update the manifest for it right now actually :ok_hand:

**Comment by Tatsh** [comment]
Thank you.

**Pull request merged**
